# Generated by Django 3.2 on 2021-11-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='user_role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
