# Generated by Django 3.2 on 2021-11-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20211108_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='user_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
