# Generated by Django 3.2 on 2021-12-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_invitation_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/06/12/10/44h4qj5q9pG47GkdpG/'),
        ),
    ]
