# Generated by Django 3.2 on 2021-12-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_invitation_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/09/13/31/087JddlR4j7C21NDDd/'),
        ),
    ]
