# Generated by Django 3.2 on 2021-12-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_auto_20211209_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/09/16/46/59vk1QKBSCn0RrwtTl/'),
        ),
    ]
