# Generated by Django 3.2 on 2021-12-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_alter_invitation_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='picture',
        ),
        migrations.AddField(
            model_name='invitation',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/15/15/21/56CRm6QmRHnw8pw8ch/'),
        ),
    ]
