# Generated by Django 3.2 on 2022-02-02 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_auto_20211215_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invitation',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/02/02/13/35/50pFNcHCmM4N95HMr4/'),
        ),
    ]
