# Generated by Django 3.2 on 2021-11-04 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('partner_email', models.CharField(blank=True, max_length=200, null=True)),
                ('partner_role', models.CharField(blank=True, max_length=200, null=True)),
                ('partner_last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('partner_picture', models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/04/06/56/05/')),
                ('currency', models.CharField(blank=True, default='GHS', max_length=128)),
                ('venue', models.CharField(blank=True, max_length=1028, null=True)),
                ('expected_guests', models.IntegerField(default=0)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, max_length=200, null=True)),
                ('end_time', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('hashtag', models.CharField(blank=True, max_length=1028, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weddings', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_wedding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Weddings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WeddingRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='weddings.wedding')),
            ],
            options={
                'verbose_name_plural': 'Wedding Roles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WeddingTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/04/06/56/05/')),
                ('display_on_wedding_page', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='weddings.weddingrole')),
                ('wedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='weddings.wedding')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/04/06/56/05/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='weddings.wedding')),
            ],
            options={
                'verbose_name_plural': 'Wedding Media',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WallPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='WALLPOST/2021/11/04/06/56/05/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallpost', to=settings.AUTH_USER_MODEL)),
                ('wedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallpost', to='weddings.wedding')),
            ],
        ),
    ]
