# Generated by Django 3.2 on 2021-11-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0004_auto_20211105_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='WALLPOST/2021/11/05/11/26/16/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='partner_picture',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/05/11/26/16/'),
        ),
        migrations.AlterField(
            model_name='weddingmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/05/11/26/16/'),
        ),
        migrations.AlterField(
            model_name='weddingteam',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/05/11/26/16/'),
        ),
    ]
