# Generated by Django 3.2 on 2021-11-08 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weddings', '0008_auto_20211108_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingmedia',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='WALLPOST/2021/11/08/10/30/10/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='couple_picture',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/08/10/30/10/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='partner_picture',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/08/10/30/10/'),
        ),
        migrations.AlterField(
            model_name='weddingmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/08/10/30/10/'),
        ),
        migrations.AlterField(
            model_name='weddingteam',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/08/10/30/10/'),
        ),
    ]
