# Generated by Django 3.2 on 2021-11-11 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weddings', '0011_auto_20211111_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='admin',
        ),
        migrations.AddField(
            model_name='wedding',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='wedding_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weddingrole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='WALLPOST/2021/11/11/19/47/08/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='couple_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/11/11/19/47/08/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='partner_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/11/11/19/47/08/'),
        ),
        migrations.AlterField(
            model_name='weddingmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/11/19/47/08/'),
        ),
        migrations.AlterField(
            model_name='weddingteam',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/11/19/47/08/'),
        ),
    ]
