# Generated by Django 3.2 on 2021-11-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0019_auto_20211125_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wedding',
            options={'ordering': ('wedding_date',), 'verbose_name_plural': 'Weddings'},
        ),
        migrations.AddField(
            model_name='wedding',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='WALLPOST/2021/11/29/20/07/25/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='couple_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/11/29/20/07/25/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='partner_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/11/29/20/07/25/'),
        ),
        migrations.AlterField(
            model_name='weddingmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/29/20/07/25/'),
        ),
        migrations.AlterField(
            model_name='weddingteam',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/29/20/07/25/'),
        ),
    ]
