# Generated by Django 3.2 on 2021-12-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0023_auto_20211204_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingteam',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='WALLPOST/2021/12/09/13/31/04mGdJN8GspgmLBG42/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='couple_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/09/13/31/04v4tqB8nlC8mv6d0p/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='partner_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/09/13/31/04v4tqB8nlC8mv6d0p/'),
        ),
        migrations.AlterField(
            model_name='weddingmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/12/09/13/31/04v4tqB8nlC8mv6d0p/'),
        ),
        migrations.AlterField(
            model_name='weddingteam',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/12/09/13/31/04v4tqB8nlC8mv6d0p/'),
        ),
    ]
