# Generated by Django 3.2 on 2021-12-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0025_auto_20211209_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingteam',
            name='picture',
        ),
        migrations.AddField(
            model_name='weddingteam',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/15/15/22/1337mLNpKhRR15dlBk/'),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='WALLPOST/2021/12/15/15/22/13wpJ63T795RsnMcLJ/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='couple_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/15/15/22/1337mLNpKhRR15dlBk/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='partner_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/15/15/22/1337mLNpKhRR15dlBk/'),
        ),
        migrations.AlterField(
            model_name='weddingmedia',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/15/15/22/1337mLNpKhRR15dlBk/'),
        ),
    ]
