# Generated by Django 3.2 on 2021-12-20 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weddings', '0026_auto_20211215_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='wedding_team',
            field=models.ManyToManyField(blank=True, related_name='wedding_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='WALLPOST/2021/12/20/04/07/259f4jB6t55CBrN4Jn/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='couple_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/20/04/07/25G6G8h90rr8JpGrbC/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='partner_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/20/04/07/25G6G8h90rr8JpGrbC/'),
        ),
        migrations.AlterField(
            model_name='weddingmedia',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/20/04/07/25G6G8h90rr8JpGrbC/'),
        ),
        migrations.AlterField(
            model_name='weddingteam',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/20/04/07/25G6G8h90rr8JpGrbC/'),
        ),
    ]
