# Generated by Django 3.2 on 2022-02-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0030_auto_20220115_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='WALLPOST/2022/02/06/03/30/46L2f7hlmQGRvfRMLD/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='couple_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/02/06/03/30/46PLKnRl9G2NhR2FN0/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='partner_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/02/06/03/30/46PLKnRl9G2NhR2FN0/'),
        ),
        migrations.AlterField(
            model_name='weddingmedia',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/02/06/03/30/46PLKnRl9G2NhR2FN0/'),
        ),
        migrations.AlterField(
            model_name='weddingteam',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/02/06/03/30/46PLKnRl9G2NhR2FN0/'),
        ),
    ]
