# Generated by Django 3.2 on 2022-02-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0031_auto_20220206_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='WALLPOST/2022/02/18/13/09/525RS5mpvmMrdMQwqt/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='couple_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/02/18/13/09/5201r3bFcM2Dn8wlpc/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='partner_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/02/18/13/09/5201r3bFcM2Dn8wlpc/'),
        ),
        migrations.AlterField(
            model_name='weddingmedia',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/02/18/13/09/5201r3bFcM2Dn8wlpc/'),
        ),
        migrations.AlterField(
            model_name='weddingteam',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/02/18/13/09/5201r3bFcM2Dn8wlpc/'),
        ),
    ]
