# Generated by Django 3.2 on 2022-05-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0035_auto_20220503_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='WALLPOST/2022/05/03/15/52/25j10jbbSmJKHh6l5P/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='couple_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/05/03/15/52/250dlMGlt4gw4g1P0n/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='couple_picture_mobile',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/05/03/15/52/250dlMGlt4gw4g1P0n/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='partner_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/05/03/15/52/250dlMGlt4gw4g1P0n/'),
        ),
        migrations.AlterField(
            model_name='weddingmedia',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/05/03/15/52/250dlMGlt4gw4g1P0n/'),
        ),
        migrations.AlterField(
            model_name='weddingteam',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/05/03/15/52/250dlMGlt4gw4g1P0n/'),
        ),
    ]
