# Generated by Django 3.2 on 2021-11-04 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Checklist Category'},
        ),
        migrations.RenameField(
            model_name='checklistcategory',
            old_name='title',
            new_name='identifier',
        ),
        migrations.AddField(
            model_name='checklist',
            name='identifier',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='checklistcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistcategory',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='checklistschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistschedule',
            name='identifier',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
