# Generated by Django 3.2 on 2021-11-05 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_auto_20211104_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='time_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='checklists.checklistschedule'),
        ),
    ]
