# Generated by Django 3.2 on 2021-11-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='events',
        ),
        migrations.AddField(
            model_name='guest',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='guests', to='guests.GuestEvent'),
        ),
    ]
