# Generated by Django 3.2 on 2021-11-11 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20211111_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='guests.guestgroup'),
        ),
        migrations.AddField(
            model_name='guest',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='guests', to='guests.GuestEvent'),
        ),
    ]
