# Generated by Django 3.2 on 2021-11-17 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guests', '0003_auto_20211111_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestevent',
            name='num_of_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guestgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestgroup',
            name='num_of_guests',
            field=models.IntegerField(default=0),
        ),
    ]
