# Generated by Django 3.2 on 2021-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_auto_20211117_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='events',
        ),
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='guestgroup',
            name='full_group_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='guestgroup',
            name='is_partner',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='guestgroup',
            name='is_wedding_creator',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='guestgroup',
            name='wedding_creator_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='guestgroup',
            name='wedding_partner_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
