# Generated by Django 3.2 on 2021-11-19 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weddings', '0018_auto_20211119_1646'),
        ('guests', '0005_auto_20211119_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestevent',
            old_name='num_of_guests',
            new_name='confirmed_guests',
        ),
        migrations.AddField(
            model_name='guestevent',
            name='guests_cancelled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guestevent',
            name='invited_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guestevent',
            name='pending_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GuestInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests_invitations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests_invitations', to='guests.guestgroup')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests_invitations', to='guests.guest')),
                ('wedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests_invitations', to='weddings.wedding')),
            ],
            options={
                'verbose_name_plural': 'Guests Invitations',
                'ordering': ('-created_at',),
            },
        ),
    ]
