# Generated by Django 3.2 on 2021-12-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_auto_20211120_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestinvitation',
            name='invite_sent',
            field=models.BooleanField(default=False),
        ),
    ]
