# Generated by Django 3.2 on 2022-01-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_guestinvitation_invite_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='companion_first_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='companion_last_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='has_companion',
            field=models.BooleanField(default=False),
        ),
    ]
