# Generated by Django 3.2 on 2022-01-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0009_auto_20220104_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email_invitation_sent',
            field=models.BooleanField(default=False),
        ),
    ]
