# Generated by Django 3.2 on 2022-02-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0010_guest_email_invitation_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='country_code',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
