# Generated by Django 3.2 on 2021-11-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211104_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='afuser',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/05/04/18/53/', verbose_name='Profile Pic'),
        ),
    ]
