# Generated by Django 3.2 on 2021-11-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211105_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/05/10/49/00/', verbose_name='Profile Pic'),
        ),
    ]
