# Generated by Django 3.2 on 2021-11-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_afuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/05/11/26/16/', verbose_name='Profile Pic'),
        ),
    ]
