# Generated by Django 3.2 on 2021-11-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_afuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='PROFILE/2021/11/05/14/04/04/', verbose_name='Profile Pic'),
        ),
        migrations.AlterField(
            model_name='afuser',
            name='wedding_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
