# Generated by Django 3.2 on 2021-11-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_afuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='afuser',
            name='is_wedding_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/11/11/12/44/48/', verbose_name='Profile Pic'),
        ),
    ]
