# Generated by Django 3.2 on 2021-11-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211111_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/11/11/21/35/43/', verbose_name='Profile Pic'),
        ),
    ]
