# Generated by Django 3.2 on 2021-12-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_afuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='afuser',
            name='has_multiple_weddings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/16/18/45/23jldtb14CnC7C9csN/', verbose_name='Profile Pic'),
        ),
    ]
