# Generated by Django 3.2 on 2021-12-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211216_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='afuser',
            name='has_created_wedding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/23/11/08/06rgpfst26CwKDNtd4/', verbose_name='Profile Pic'),
        ),
    ]
