# Generated by Django 3.2 on 2021-12-23 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20211223_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/23/12/50/024Dlcn5Qq7Lgn5d9f/', verbose_name='Profile Pic'),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_in_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification',
                'ordering': ('-date_created',),
            },
        ),
    ]
