# Generated by Django 3.2 on 2021-12-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211223_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2021/12/23/13/14/05mMf5pPk7gn1k3FP0/', verbose_name='Profile Pic'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='object_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
