# Generated by Django 3.2 on 2022-01-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20211223_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='afuser',
            name='author_role',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/01/15/10/42/160K440Q2BtF0gwgS3/', verbose_name='Profile Pic'),
        ),
    ]
