# Generated by Django 3.2 on 2022-02-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220115_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='afuser',
            name='is_beta_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/02/04/18/17/18TmFsgnd9hqn7MJc1/', verbose_name='Profile Pic'),
        ),
    ]
