# Generated by Django 3.2 on 2022-02-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220206_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/02/18/13/10/00FbvjKwwP1qQwbd1T/', verbose_name='Profile Pic'),
        ),
    ]
