# Generated by Django 3.2 on 2022-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_afuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='afuser',
            name='country_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/02/18/13/18/14L5TH2sflRl6DN6Gf/', verbose_name='Profile Pic'),
        ),
    ]
