# Generated by Django 3.2 on 2022-05-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220218_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='afuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='afuser',
            name='vendor_display_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='afuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='PROFILE/2022/05/02/12/23/45P05bPDgR9Q6R8BRD/', verbose_name='Profile Pic'),
        ),
    ]
