# Generated by Django 3.2 on 2021-12-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rsvp', '0003_rsvpquestion_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='rsvp.rsvpquestion')),
            ],
            options={
                'verbose_name_plural': 'RSVP Answer',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='rsvp',
            name='rsvp_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='rsvp.rsvpanswer'),
        ),
    ]
