# Generated by Django 3.2 on 2021-12-06 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0004_defaultfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRSVPQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Default RSVP Question',
                'ordering': ('id',),
            },
        ),
    ]
