# Generated by Django 3.2 on 2021-12-06 17:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0005_defaultrsvpquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=2000, null=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default='5000', max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Default Budget',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DefaultBudgetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Default Budget Category',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DefaultBudgetExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_expense', to='prerequisites.defaultbudgetcategory')),
            ],
            options={
                'verbose_name_plural': 'Default Budget Expense',
                'ordering': ('id',),
            },
        ),
    ]
