# Generated by Django 3.2 on 2022-01-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0006_defaultbudget_defaultbudgetcategory_defaultbudgetexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultchecklist',
            name='intent',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
