# Generated by Django 3.2 on 2022-02-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0008_defaultguestevent_defaultscheduleevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultGuestEvent',
            new_name='DefaultWeddingEvent',
        ),
        migrations.DeleteModel(
            name='DefaultScheduleEvent',
        ),
        migrations.AlterModelOptions(
            name='defaultweddingevent',
            options={'ordering': ('name',), 'verbose_name_plural': 'Default Wedding Events'},
        ),
    ]
