# Generated by Django 3.2 on 2021-11-04 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('currency', models.CharField(blank=True, max_length=2000, null=True)),
                ('total_estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_pending', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to=settings.AUTH_USER_MODEL)),
                ('wedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='weddings.wedding')),
            ],
            options={
                'verbose_name_plural': 'Budget Category',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BudgetExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('currency', models.CharField(blank=True, max_length=2000, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('pending', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_expense', to='budget.budgetcategory')),
            ],
            options={
                'verbose_name_plural': 'Budget Expense',
                'ordering': ('-created_at',),
            },
        ),
    ]
