# Generated by Django 3.2 on 2021-11-05 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetexpense',
            old_name='actual_cost',
            new_name='final_cost',
        ),
        migrations.AddField(
            model_name='budgetexpense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_expense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetexpense',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paid_by', models.CharField(blank=True, max_length=2000, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=2000, null=True)),
                ('payment_due', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=2000, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='budget.budgetexpense')),
            ],
            options={
                'verbose_name_plural': 'Expense Payment',
                'ordering': ('-created_at',),
            },
        ),
    ]
