# Generated by Django 3.2 on 2021-11-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20211105_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='total_estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='total_final_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='total_pending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='budgetexpense',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='budgetexpense',
            name='pending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
